version: "3"
services:
#  app:
#    build: ./app
#    container_name: 'python'
#    links:
#      - db
#    ports:
#      - "5555:5000"

  db:
    container_name: 'mysql'
    image: mariadb
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro