version: "3"
services:
  alpine:
    container_name: 'my_little_alpine'
    build: .
    ports:
      - "8122:81"
    volumes:
      - ./data/input:/input
      - ./data/output:/output
    command: tail -F /temp
  db:
    container_name: 'mysql_db'
    image: mariadb
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro