version: "3"
services:
  alpine:
    container_name: 'my_little_alpine'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8122:81"
    volumes:
      - ./data/input:/input
      - ./data/output:/output
    command: tail -F /temp
#  theglassfish:
#    container_name: 'theglassfish'
#    image: glassfish
#    ports:
#      - "8123:81"
#    volumes:
#      - ./data/input:/input
#      - ./data/output:/output
#    command: bash -c "tail -F /temp && COPY target/application.war $GLASSFISH_HOME/glassfish/domains/domain1/autodeploy/"
  db:
    container_name: 'mysql_db'
    image: mariadb
    command: --default-authentication-plugin=caching_sha2_password
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro